config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/privacy", to: "static_pages#privacy"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/oauth/:provider", to: "oauths#create", as: :oauth

  resources :users do
    member do
      get :following, to: "relationships#index", relationship: :following
      get :followers, to: "relationships#index", relationship: :followers
    end
  end
  
  resources :posts, only: [:create, :destroy, :show] do
    member do
      patch :like, to: "likes#update"
      post :comment, to: "comments#create"
      post :share, to: "shares#create"
    end
  end

  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  # resources :notifications, only: [:index, :update, :show]
  get "/notification", to: "notifications#new"
  get "/notifications", to: "notifications#index"
  get "/notifications/show", to: "notifications#show"
  patch "/notifications/update", to: "notifications#update"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if login?
      @post = Post.new
      @share = current_user.share
      @comment = current_user.comment
      @feeds_collection = current_user.feed
      @pagy, @feeds = pagy(@feeds_collection)
    end
  end

  def about
  end

  def help
  end

  def contact
  end

  def privacy
  end

end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h2>About This Website</h2>

<div id="introduction" class="my-5">
  <a href="https://travis-ci.org/kuei0221/tweet-demo"><img src="https://travis-ci.org/kuei0221/tweet-demo.svg?branch=master"></a>
  <p>This is a Twitter website mocking project, focusing on rebuilding the commonlu used function in the social website.</p>
  <p>The project is started by following the instruction of the book: Ruby on Rail Tutorial written by Michael Hartl, and then implementing various external service to fulfill the completence.</p>
  <p>This project is only for academic research, not for any commerical usage.</p>
</div>

<div id="features" class="my-5">
  <h3>Features: </h3>
  <ul>
    <li>Manually built user system based on the understanding of session and cookies.</li>
    <li>Mailing is allowed through Mailgun service when user authorizing and password reset.</li>
    <li>User is enabled to create their post, and also can like, share and comment on the post. The link of the post is also provided.</li>
    <li>User can follow other users to get other users' post in their home page.</li>
    <li>User can upload their own avatar when creating account or uploading. If no avatar when creating, attaching default avatar instead.</li>
    <li>Allow login through Facebook or Google account with oauth2 authenticating process.</li>
    <li>
      <h6>Notification system build with Pusher</h6>
      <ul>
        <li>Realtime notifnication push when other user does action on their post. (currently just like)</li>
        <li>Showing how much unread notification, and clear the counting once read.</li>
        <li>Can view through their own notification history.</li>
      </ul>
    </li>
  </ul>
</div>

<div id="environment" class="my-5">

  <h3>Environment: </h3>
  <ul>
    <li>Rails 5.2.3</li>
    <li>Ruby 2.6.3</li>
    <li>RVM 1.29.9</li>
    <li>Ubuntu 18.04.3 LTS under Win10</li>
    <li>
      <h6>Service</h6>
      <ul>
        <li><a href="https://www.heroku.com/">Heroku</a> for deployment</li>
        <li><a href="https://www.postgresql.org/">postgresql</a> as database</li>
        <li><a href="https://developers.facebook.com/">Facebook</a> and <a href="https://developers.google.com/identity/choose-auth">Google</a> for oauth2 login</li>
        <li><a href="https://aws.amazon.com/tw/s3/">Amazon S3</a> as image storage</li>
        <li><a href="https://www.mailgun.com/">Mailgun</a> for mailing</li>
        <li><a href="https://pusher.com/">Pusher</a> for notification</li>
        <li><a href="https://enterprise.travis-ci.com/">Travis-ci</a> for CI </li>
        <li><a href="https://github.com/">git</a> for version control</li>
        <li><a href="https://www.privacypolicies.com">privacypolicies</a> for privacy</li>
      </ul>
    </li>
  </ul>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if login? %>
  <div class = "row">
    <div class="col-4">
      <%= show_errors @post %>
      <%= render "shared/user_info", user: current_user %>
      <div class="card mt-3">
        <div class="body">
          <%= render "posts/post_form" %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <h3 class="text-center">Micropost Feed</h3>
      <%= show_feed @feeds %>
    </div>
  </div>
<% else %>
  <div class="row justify-content-center text-center">
    <div class="col-8">
      <h2>Welcome to the Tweet-demo !</h2>
      <p>Please Login to see more content!</p>
      <p><%= link_to "Login in", login_path %></p>
      <p><%= link_to "Haven't sign up?", signup_path %></p>
    </div>
  </div>
  <div class="row justify-content-end pt-3">
    <%= image_tag "rails.png", style: "height:200px" %>
  </div>
<% end %>

app/views/static_pages/privacy.html.erb
<h1>Privacy Policy</h1>
<a href="https://www.privacypolicies.com/privacy/view/922d48b2d8a9754ba9a3a855fdd275ec">Resource</a>


<p>Effective date: October 08, 2019</p>


<p>mytweet-demo ("us", "we", or "our") operates the https://mytweet-demo.herokuapp.com website (hereinafter referred to as the "Service").</p>

<p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. Our Privacy Policy  for mytweet-demo is created with the help of the <a href="https://www.privacypolicies.com/free-privacy-policy-generator/">PrivacyPolicies.com Privacy Policy Generator</a>.</p>

<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://mytweet-demo.herokuapp.com</p>


<h2>Information Collection And Use</h2>

<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

<h3>Types of Data Collected</h3>

<h4>Personal Data</h4>

<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

<ul>
<li>Email address</li><li>First name and last name</li><li>Cookies and Usage Data</li>
</ul>

<h4>Usage Data</h4>

<p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

<h4>Tracking & Cookies Data</h4>
<p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
<p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. You can learn more how to manage cookies in the <a href="https://privacypolicies.com/blog/how-to-delete-cookies/">Browser Cookies Guide</a>.</p>
<p>Examples of Cookies we use:</p>
<ul>
    <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
    <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
    <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
</ul>

<h2>Use of Data</h2>
    
<p>mytweet-demo uses the collected data for various purposes:</p>    
<ul>
    <li>To provide and maintain the Service</li>
    <li>To notify you about changes to our Service</li>
    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
    <li>To provide customer care and support</li>
    <li>To provide analysis or valuable information so that we can improve the Service</li>
    <li>To monitor the usage of the Service</li>
    <li>To detect, prevent and address technical issues</li>
</ul>

<h2>Transfer Of Data</h2>
<p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
<p>If you are located outside Taiwan and choose to provide information to us, please note that we transfer the data, including Personal Data, to Taiwan and process it there.</p>
<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
<p>mytweet-demo will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

<h2>Disclosure Of Data</h2>

<h3>Legal Requirements</h3>
<p>mytweet-demo may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
    <li>To comply with a legal obligation</li>
    <li>To protect and defend the rights or property of mytweet-demo</li>
    <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
    <li>To protect the personal safety of users of the Service or the public</li>
    <li>To protect against legal liability</li>
</ul>

<h2>Security Of Data</h2>
<p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

<h2>Service Providers</h2>
<p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>



<h2>Links To Other Sites</h2>
<p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>


<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 18 ("Children").</p>
<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>


<h2>Changes To This Privacy Policy</h2>
<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>


<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, please contact us:</p>
<ul>
  <li>By email: michaelhwang0619@gmail.com</li>
</ul>