config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/privacy", to: "static_pages#privacy"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/oauth/:provider", to: "oauths#create", as: :oauth

  resources :users do
    member do
      get :following, to: "relationships#index", relationship: :following
      get :followers, to: "relationships#index", relationship: :followers
    end
  end
  
  resources :posts, only: [:create, :destroy, :show] do
    member do
      patch :like, to: "likes#update"
      post :comment, to: "comments#create"
      post :share, to: "shares#create"
    end
  end

  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  # resources :notifications, only: [:index, :update, :show]
  get "/notification", to: "notifications#new"
  get "/notifications", to: "notifications#index"
  get "/notifications/show", to: "notifications#show"
  patch "/notifications/update", to: "notifications#update"
end

app/views/shared/_dropdown_form.html.erb
<div class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    <%= fa_icon(icon, text: post.send(counter), id: "#{action}-icon") %>
  </a>
  <div class="dropdown-menu justify-content-start">
    <%= form_for(Micropost.new, url: "/posts/#{post.id}/#{action}", remote: true) do |f| %>
      <%= f.text_field :content, class: "dropdown-item", style: "width: 550px", placeholder: "#{action.capitalize}:" %>
    <% end %>
  </div>
</div>

app/views/shared/_micropost_content.html.erb
<p class="card-text p-0"><%= link_to micropost.content, post_path(micropost.id), class: "text-dark", id: "content-#{micropost.id}" %></p>
<%= image_tag micropost.picture if micropost.picture.attached? %>

app/views/shared/_micropost_title.html.erb
<h5 class="card-title">
  <%= link_to micropost.user.name, user_path(micropost.user), class: "text-info" %>
  <small class="text-muted">． <%= time_ago_in_words(micropost.created_at) %> ago</small>
</h5>

app/views/shared/_notification.html.erb
<% bg_color = notification.new? ? "bg-light" : "bg-white" %>
<div class="dropdown-item py-0 <%= bg_color %> notifications" id="<%= notification.id%>">
  <div class="row">
    <div class="col-2 pl-0">
      <% if notification.feeder_avatar.attached? %>
        <%= image_tag notification.feeder_avatar, style: "height: 50px; width: 50px" %>
      <% end %>
    </div>
    <div class="col-10">
      <%= link_to notification.message, notification.micropost %>
      <p class="text-left"><small class="text-muted"><%= time_ago_in_words(notification.created_at) %> ago</small></p>
    </div>
  </div>
  <div class="dropdown-divider mt-0"></div>
</div>

app/views/shared/_user_info.html.erb
<div class="card">
  <%= show_avatar(user, "card-img-top") %>
  <div class="card-body">
    <div class="row">
      <div class="col-8">
        <h5 class="card-title"><%= user.name %></h5>
        <p class="card-subtitle text-muted"><%= user.email%></p>
      </div>
      <div class="col-4">
       <%= follow_button_html(user) %>
      </div>
    </div>
    <div class="row py-3">
      <div class="col">
        <%= link_to "Followers: #{ user.followers_count }", followers_user_path(user) %>
      </div>
      <div class="col">
        <%= link_to "Following: #{ user.following_count }", following_user_path(user) %>
      </div>
    </div>
    <%= edit_button user %>
  </div>
</div>