config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/privacy", to: "static_pages#privacy"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/oauth/:provider", to: "oauths#create", as: :oauth

  resources :users do
    member do
      get :following, to: "relationships#index", relationship: :following
      get :followers, to: "relationships#index", relationship: :followers
    end
  end
  
  resources :posts, only: [:create, :destroy, :show] do
    member do
      patch :like, to: "likes#update"
      post :comment, to: "comments#create"
      post :share, to: "shares#create"
    end
  end

  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  # resources :notifications, only: [:index, :update, :show]
  get "/notification", to: "notifications#new"
  get "/notifications", to: "notifications#index"
  get "/notifications/show", to: "notifications#show"
  patch "/notifications/update", to: "notifications#update"
end

app/models/post.rb
class Post < Micropost
  has_many :comments

  has_one :sharing_relationship, class_name: "Share", foreign_key: "shared_id"
  has_one :sharing, through: :sharing_relationship, source: :sharing

  has_many :shared_relationship, class_name: "Share", foreign_key: "sharing_id"
  has_many :shared, through: :shared_relationship, source: :shared

  default_scope -> { order(created_at: :desc)}
  scope :feed, -> (user) { where("user_id IN (?) or user_id = ? ", user.following_ids, user.id) }
  # scope :random, -> (nums=1) { unscoped.order("RANDOM()").limit(nums) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :is_login?, only: [:create]
  before_action :correct_author, only: [:destroy]

  def show
    @post = Post.includes(:liked_users, :sharing, user:{avatar_attachment: :blob}).find_by(id: params[:id])
    @comments = @post.comments.includes(:liked_users, user: {avatar_attachment: :blob} ).all
    # @comment = Comment.new
    # which is better? create a empty instance vairable or create in form?
  end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        flash[:success] = "Create Post success"
        format.js
        format.html { redirect_to root_url }
      else
        flash[:danger] = "Invalid post"
        format.html {redirect_back fallback_location: root_url}
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to current_user
  end

  private

  def post_params
    params.require(:post).permit(:content, :picture)
  end

  def correct_author
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def show_sharing_post(post)

    if post.sharing.present?
      render "shares/share", share: post.sharing
    else
      return nil
    end

  end
  
end

app/views/posts/_post.html.erb
<div class="card my-3" id="post-<%= post.id %>">

  <div class="row no-gutters">
    
    <div class="col-2">
      <% cache [post.user, post.user.avatar_attachment] do %>
        <%= show_avatar post.user, "card-img", nil %>
      <% end %>
    </div>

    <div class="col-9">
      <div class="card-body">
        <%= render "shared/micropost_title", micropost: post %>
        <%= render "shared/micropost_content", micropost: post %>
        <div style="width: 100%">
        <% cache [post.id, "sharing", post.sharing, post.user, post.user.avatar_attachment] do %>
          <%= show_sharing_post post %>
        <% end %>
        </div>
      </div>
    </div>

  </div>

  <div class="card-footer p-0">
    <div class = "row" id="bar-<%= post.id %>">
      <%= render "posts/post_function_bar", post: post %>
    </div>
  </div>

</div>

app/views/posts/_post_form.html.erb
<%= form_for(@post, url: posts_path, remote: true) do |f| %>

  <%= f.text_area :content, class: "form-control", placeholder: "New Post" %>

  <%= f.submit "Create new post", class: "btn btn-primary btn-lg btn-block" %>
  <%= f.file_field :picture %>
<% end %>

app/views/posts/_post_function_bar.html.erb
<div class="col-2" id="comment_form">
  <% cache [post.id, "comment", post.comments_count, current_user.id] do %>
    <%= render "comments/comment_form", post: post %>
  <% end %>
</div>

<div class="col-2" id="share_form">
  <% cache [post.id, "share", post.shares_count, current_user.id] do %>
    <%= render "shares/share_form", post: post %>
  <% end %>
</div>

<div class="col-2" id="like_button">
  <% cache [post.id, "like", post.likes_count, current_user.id] do %>
    <%= like_button(post)%>
  <% end %>
</div>

<div class="col-2">
  <button class="clipboard btn" id= "" data-clipboard-text="<%= post_url(post.id) %>">
    <%= fa_icon("link") %>
  </button>
</div>

app/views/posts/create.js.erb
$(".pagy-bootstrap-nav").after("<%= j render "posts/post", post: @post %>");

app/views/posts/show.html.erb
<div class="row justify-content-center">
 
  <div class="col-8">
    <%= render "post", post: @post %>
    <%= render @comments %>
  </div>
</div>