config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/privacy", to: "static_pages#privacy"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/oauth/:provider", to: "oauths#create", as: :oauth

  resources :users do
    member do
      get :following, to: "relationships#index", relationship: :following
      get :followers, to: "relationships#index", relationship: :followers
    end
  end
  
  resources :posts, only: [:create, :destroy, :show] do
    member do
      patch :like, to: "likes#update"
      post :comment, to: "comments#create"
      post :share, to: "shares#create"
    end
  end

  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  # resources :notifications, only: [:index, :update, :show]
  get "/notification", to: "notifications#new"
  get "/notifications", to: "notifications#index"
  get "/notifications/show", to: "notifications#show"
  patch "/notifications/update", to: "notifications#update"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <ul class="nav nav-tabs justify-content-end pr-5 my-5">
    <li class="nav-item">
      <%= link_to "Help", help_path, class: "nav-link " %> 
    </li>
    
    <li class="nav-item">
      <%= link_to "Privacy", privacy_path, class: "nav-link" %>
    </li>

    <li class="nav-item">
      <%= link_to "Contact", contact_path, class: "nav-link" %>
    </li>
    
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to "Home", root_url, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class:"nav-link" %>
        </li>
        <%= dropdown_header %>
    </ul> 
  </div>
</header>

app/views/layouts/_header_login.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
  <div class="dropdown-menu">
    <%= link_to "Profile", user_path(session[:user_id]), class:"dropdown-item" %>
    <div class="dropdown-divider"></div>
    <%= link_to "Logout", logout_path, method: "delete", class:"dropdown-item" %>
  </div>
</li>

<li class="nav-item dropdown ml-auto">
  <a class="nav-link dropdown-toggle" id="notification_button" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Notification: <span><%= current_user.notifications.unread.size%></span></a>
  <div class="dropdown-menu dropdown-menu-right" id="notification_box">
    <button class="dropdown-item text-center py-0" id="loadmore-button">Load more</button>
  </div>
</li>

app/views/layouts/_header_not_login.html.erb
<li class="nav-item">
  <%= link_to "Login", login_path, class:"nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "Sign up", new_user_path, class:"nav-link" %>
</li>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<script src="https://apis.google.com/js/platform.js" async defer></script>
<script src="//js.pusher.com/4.4/pusher.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>

    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
  </head>

  <body style="width: 1280px; height: 550px">
    <%= render "layouts/header" %>
    <div class="container py-5">
      <% show_flash %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>